Testing nested try statement, with try statement nested in catch clause