Testing nested try statements with try nested in catch 